export const designations = [
    "Accountant (Junior)",
    "Accounts Payable/Receivable Clerk",
    "Actuary",
    "Affiliate Marketing Manager",
    "AI/ML Developer (Artificial Intelligence/Machine Learning)",
    "Audit Manager",
    "Back Office Executive",
    "Back Office Manager",
    "Backend Developer",
    "Backend Developer (Junior)",
    "Benefits Administrator",
    "Blockchain Developer",
    "Bookkeeper",
    "Brand Manager",
    "Budget Analyst",
    "Budget Manager",
    "Business Development Manager",
    "Business Development Representative (BDR)",
    "Call Center Agent",
    "Call Center Manager",
    "Call Center Supervisor",
    "Channel Sales Representative",
    "Chat Support Executive",
    "Chief Financial Officer (CFO)",
    "Chief Human Resources Officer (CHRO)",
    "Chief Investment Officer (CIO)",
    "Chief Marketing Officer (CMO)",
    "Chief Sales Officer (CSO)",
    "Chief Technology Officer (CTO)",
    "Client Relationship Manager",
    "Cloud Engineer",
    "Compensation Analyst",
    "Compensation and Benefits Manager",
    "Compliance Officer",
    "Content Marketing Associate",
    "Content Marketing Specialist",
    "Content Moderator",
    "Content Strategist",
    "Corporate Finance Manager",
    "Cost Accountant",
    "Creative Director",
    "Credit Analyst",
    "Customer Service Representative (CSR)",
    "Customer Success Manager (CSM)",
    "Customer Support Manager (Non-Voice)",
    "Customer Support Manager (Voice)",
    "Cybersecurity Developer",
    "Data Entry Specialist",
    "Data Scientist",
    "Demand Generation Manager",
    "Developer",
    "DevOps Engineer",
    "Digital Marketing",
    "Digital Marketing Assistant",
    "Digital Marketing Specialist",
    "Director of Brand Strategy",
    "Director of Digital Marketing",
    "Director of Finance",
    "Director of Financial Operations",
    "Director of Talent Acquisition",
    "Diversity and Inclusion Manager",
    "E-commerce Marketing Manager",
    "Email Marketing Coordinator",
    "Email Marketing Manager",
    "Email Support Representative",
    "Email/Chat Support Supervisor",
    "Embedded Systems Developer",
    "Employee Experience Manager",
    "Employee Relations Manager",
    "Engineering Manager",
    "Enterprise Sales Executive",
    "Equity Analyst",
    "Event Marketing Manager",
    "Field Sales Representative",
    "Finance Assistant",
    "Finance Director",
    "Finance Manager",
    "Financial Analyst",
    "Financial Analyst (Junior)",
    "Financial Consultant",
    "Financial Controller",
    "Financial Planning and Analysis (FP&A) Analyst",
    "Forensic Accountant",
    "Frontend Developer",
    "Frontend Developer (Junior)",
    "Full-Stack Developer",
    "Full-Stack Developer (Junior)",
    "Game Developer",
    "Growth Hacker",
    "Growth Marketing Lead",
    "Growth Marketing Manager",
    "Head of Engineering",
    "Head of Financial Planning and Analysis (FP&A)",
    "Head of Marketing",
    "Head of People Operations",
    "Head of Sales",
    "Head of Treasury",
    "Hedge Fund Analyst",
    "Help Desk Support (Voice)",
    "HR Assistant",
    "HR Clerk",
    "HR Coordinator",
    "HR Director",
    "HR Generalist",
    "HR Specialist",
    "Inbound/Outbound Call Agent",
    "Influencer Marketing Manager",
    "Inside Sales Representative",
    "Internal Auditor",
    "Investment Analyst",
    "Investment Analyst (Junior)",
    "Investment Banker",
    "Investment Manager",
    "IoT Developer (Internet of Things)",
    "Java Android",
    "Java Developer",
    "Junior Developer",
    "Junior Software Engineer",
    "Key Account Manager",
    "Lead Developer",
    "Learning and Development Manager",
    "Loan Officer",
    "Marketing Analyst",
    "Marketing Assistant",
    "Marketing Automation Specialist",
    "Marketing Communications Manager",
    "Marketing Coordinator",
    "Marketing Director",
    "Marketing Intern",
    "Marketing Specialist",
    "MERN Stack Developer",
    "Mergers and Acquisitions (M&A) Manager",
    "Mobile App Developer",
    "Mobile App Developer (Junior)",
    "MongoDB Developer",
    "National Sales Director",
    "NodeJs Developer",
    "Non-Voice Customer Support",
    "Non-Voice Process Manager",
    "Non-Voice Technical Support Specialist",
    "NON VOICE",
    "Operations Manager (Non-Voice)",
    "Operations Manager (Voice)",
    "Organizational Development Manager",
    "Outside Sales Representative",
    "Paid Advertising Specialist (PPC)",
    "Payroll Clerk",
    "Payroll Manager",
    "Performance Marketing Manager",
    "Phone Support Specialist",
    "Portfolio Manager",
    "Poster Designer",
    "Principal Engineer",
    "Product Marketing Manager",
    "Public Relations (PR) Manager",
    "Python Desktop Developer",
    "Python Developer",
    "Quality Analyst (Voice Process)",
    "React Native",
    "ReactJs Developer",
    "Recruiting Assistant",
    "Recruiting Manager",
    "Recruiting Specialist",
    "Regional Sales Manager",
    "Retail Sales Associate",
    "Risk Analyst",
    "Risk Manager",
    "SaaS Sales Executive (Software as a Service)",
    "Sales Associate",
    "Sales Consultant",
    "Sales Development Representative (SDR)",
    "Sales Director",
    "Sales Enablement Manager",
    "Sales Engineer",
    "Sales Executive",
    "Sales Operations Manager",
    "Sales Operations Specialist",
    "Sales Representative",
    "Sales Support Representative (Voice)",
    "Sales Team Lead (Voice)",
    "Sales Team Leader",
    "Senior Accountant",
    "Senior Backend Developer",
    "Senior Brand Manager",
    "Senior Content Strategist",
    "Senior Customer Service Representative",
    "Senior Developer",
    "Senior DevOps Engineer",
    "Senior Digital Marketing Manager",
    "Senior Financial Analyst",
    "Senior Frontend Developer",
    "Senior Full-Stack Developer",
    "Senior Manager (Call Center Operations)",
    "Senior Manager (Non-Voice Customer Service)",
    "Senior Marketing Manager",
    "Senior Mobile App Developer",
    "Senior Non-Voice Support Specialist",
    "Senior Product Marketing Manager",
    "Senior Sales Executive",
    "Senior SEO Manager",
    "Senior Software Engineer",
    "SEO Assistant",
    "SEO Manager",
    "SEO Specialist",
    "Social Media Coordinator",
    "Social Media Manager",
    "Social Media Support Executive",
    "Social Media Support Manager",
    "Social Media Support Specialist",
    "Software Developer",
    "Software Engineer",
    "Solutions Architect",
    "Solutions Sales Manager",
    "Strategic Account Manager",
    "Systems Architect",
    "Talent Acquisition Specialist",
    "Tax Advisor",
    "Tax Associate",
    "Tax Manager",
    "Tax Specialist",
    "Team Lead (Non-Voice)",
    "Team Lead (Voice)",
    "Technical Director",
    "Technical Lead",
    "Technical Sales Representative",
    "Technical Support Representative (Non-Voice)",
    "Technical Support Representative (Voice)",
    "Technical Support Specialist (Voice)",
    "Telemarketer",
    "Telemarketing Executive",
    "Territory Sales Manager",
    "Training and Development Coordinator",
    "Training and Development Manager",
    "Training Specialist (Voice)",
    "Treasury Analyst",
    "Treasury Manager",
    "UI/UX Designer",
    "Video Editor",
    "Vice President of Business Development",
    "Vice President of Finance",
    "Vice President of Human Resources",
    "Vice President of Marketing",
    "VOICE",
    "Voice Process Manager",
    "VP of Engineering",
    "VP of Growth",
    "VP of Product Marketing",
    "VP of Sales",
    "VR/AR Developer (Virtual Reality/Augmented Reality)",
    "Wealth Manager",
    "Web Developer",
];

export const designationPrefixes = {
    "Accountant (Junior)": "ACCT-JR",
    "Accounts Payable/Receivable Clerk": "AP/AR-CLK",
    "Actuary": "ACTUARY",
    "Affiliate Marketing Manager": "AFF-MKT-MGR",
    "AI/ML Developer (Artificial Intelligence/Machine Learning)": "AI/ML-DEV",
    "Audit Manager": "AUDIT-MGR",
    "Back Office Executive": "BO-EXEC",
    "Back Office Manager": "BO-MGR",
    "Backend Developer": "BE-DEV",
    "Backend Developer (Junior)": "BE-DEV-JR",
    "Benefits Administrator": "BEN-ADMIN",
    "Blockchain Developer": "BC-DEV",
    "Bookkeeper": "BKPR",
    "Brand Manager": "BRAND-MGR",
    "Budget Analyst": "BDGT-ANLY",
    "Budget Manager": "BDGT-MGR",
    "Business Development Manager": "BIZ-DEV-MGR",
    "Business Development Representative (BDR)": "BDR",
    "Call Center Agent": "CC-AGENT",
    "Call Center Manager": "CC-MGR",
    "Call Center Supervisor": "CC-SUPV",
    "Channel Sales Representative": "CHNL-SALES",
    "Chat Support Executive": "CHAT-SUPP",
    "Chief Financial Officer (CFO)": "CFO",
    "Chief Human Resources Officer (CHRO)": "CHRO",
    "Chief Investment Officer (CIO)": "CIO",
    "Chief Marketing Officer (CMO)": "CMO",
    "Chief Sales Officer (CSO)": "CSO",
    "Chief Technology Officer (CTO)": "CTO",
    "Client Relationship Manager": "CRM",
    "Cloud Engineer": "CLOUD-ENG",
    "Compensation Analyst": "COMP-ANLY",
    "Compensation and Benefits Manager": "COMP-BEN-MGR",
    "Compliance Officer": "COMP-OFF",
    "Content Marketing Associate": "CONT-MKT-ASC",
    "Content Marketing Specialist": "CONT-MKT-SP",
    "Content Moderator": "CONT-MOD",
    "Content Strategist": "CONT-STRAT",
    "Corporate Finance Manager": "CORP-FIN-MGR",
    "Cost Accountant": "COST-ACCT",
    "Creative Director": "CRTV-DIR",
    "Credit Analyst": "CRED-ANLY",
    "Customer Service Representative (CSR)": "CSR",
    "Customer Success Manager (CSM)": "CSM",
    "Customer Support Manager (Non-Voice)": "CS-MGR-NV",
    "Customer Support Manager (Voice)": "CS-MGR-V",
    "Cybersecurity Developer": "CYBR-DEV",
    "Data Entry Specialist": "DATA-ENTRY",
    "Data Scientist": "DATA-SCI",
    "Demand Generation Manager": "DEM-GEN-MGR",
    "Developer": "DEV",
    "DevOps Engineer": "DEVOPS",
    "Digital Marketing": "DIG-MKT",
    "Digital Marketing Assistant": "DIG-MKT-AST",
    "Digital Marketing Specialist": "DIG-MKT-SP",
    "Director of Brand Strategy": "DIR-BRAND",
    "Director of Digital Marketing": "DIR-DIG-MKT",
    "Director of Finance": "DIR-FIN",
    "Director of Financial Operations": "DIR-FIN-OPS",
    "Director of Talent Acquisition": "DIR-TAL-ACQ",
    "Diversity and Inclusion Manager": "D&I-MGR",
    "E-commerce Marketing Manager": "ECOM-MKT-MGR",
    "Email Marketing Coordinator": "EMAIL-MKT-COORD",
    "Email Marketing Manager": "EMAIL-MKT-MGR",
    "Email Support Representative": "EMAIL-SUPP",
    "Email/Chat Support Supervisor": "EC-SUPP-SUPV",
    "Embedded Systems Developer": "EMB-SYS-DEV",
    "Employee Experience Manager": "EMP-EXP-MGR",
    "Employee Relations Manager": "EMP-REL-MGR",
    "Engineering Manager": "ENG-MGR",
    "Enterprise Sales Executive": "ENT-SALES-EXEC",
    "Equity Analyst": "EQ-ANLY",
    "Event Marketing Manager": "EVT-MKT-MGR",
    "Field Sales Representative": "FIELD-SALES",
    "Finance Assistant": "FIN-ASST",
    "Finance Director": "FIN-DIR",
    "Finance Manager": "FIN-MGR",
    "Financial Analyst": "FIN-ANLY",
    "Financial Analyst (Junior)": "FIN-ANLY-JR",
    "Financial Consultant": "FIN-CONS",
    "Financial Controller": "FIN-CTRL",
    "Financial Planning and Analysis (FP&A) Analyst": "FP&A-ANLY",
    "Forensic Accountant": "FOR-ACCT",
    "Frontend Developer": "FE-DEV",
    "Frontend Developer (Junior)": "FE-DEV-JR",
    "Full-Stack Developer": "FULL-DEV",
    "Full-Stack Developer (Junior)": "FULL-DEV-JR",
    "Game Developer": "GAME-DEV",
    "Growth Hacker": "GRWTH-HACK",
    "Growth Marketing Lead": "GRWTH-MKT-LEAD",
    "Growth Marketing Manager": "GRWTH-MKT-MGR",
    "Head of Engineering": "HEAD-ENG",
    "Head of Financial Planning and Analysis (FP&A)": "HEAD-FP&A",
    "Head of Marketing": "HEAD-MKT",
    "Head of People Operations": "HEAD-PPL-OPS",
    "Head of Sales": "HEAD-SALES",
    "Head of Treasury": "HEAD-TREAS",
    "Hedge Fund Analyst": "HF-ANLY",
    "Help Desk Support (Voice)": "HELP-DESK-V",
    "HR Assistant": "HR-ASST",
    "HR Clerk": "HR-CLERK",
    "HR Coordinator": "HR-COORD",
    "HR Director": "HR-DIR",
    "HR Generalist": "HR-GEN",
    "HR Specialist": "HR-SPEC",
    "Inbound/Outbound Call Agent": "IN/OUT-CALL",
    "Influencer Marketing Manager": "INF-MKT-MGR",
    "Inside Sales Representative": "IN-SALES",
    "Internal Auditor": "INT-AUDIT",
    "Investment Analyst": "INV-ANLY",
    "Investment Analyst (Junior)": "INV-ANLY-JR",
    "Investment Banker": "INV-BANK",
    "Investment Manager": "INV-MGR",
    "IoT Developer (Internet of Things)": "IOT-DEV",
    "Java Android": "JAVA-AND",
    "Java Developer": "JAVA-DEV",
    "Junior Developer": "JR-DEV",
    "Junior Software Engineer": "JR-SW-ENG",
    "Key Account Manager": "KEY-ACCT-MGR",
    "Lead Developer": "LEAD-DEV",
    "Learning and Development Manager": "L&D-MGR",
    "Loan Officer": "LOAN-OFF",
    "Marketing Analyst": "MKT-ANLY",
    "Marketing Assistant": "MKT-ASST",
    "Marketing Automation Specialist": "MKT-AUTO-SP",
    "Marketing Communications Manager": "MKT-COMM-MGR",
    "Marketing Coordinator": "MKT-COORD",
    "Marketing Director": "MKT-DIR",
    "Marketing Intern": "MKT-INTERN",
    "Marketing Specialist": "MKT-SPEC",
    "MERN Stack Developer": "MERN-DEV",
    "Mergers and Acquisitions (M&A) Manager": "M&A-MGR",
    "Mobile App Developer": "MOB-APP-DEV",
    "Mobile App Developer (Junior)": "MOB-APP-DEV-JR",
    "MongoDB Developer": "MONGO-DEV",
    "National Sales Director": "NAT-SALES-DIR",
    "NodeJs Developer": "NODE-DEV",
    "Non-Voice Customer Support": "NV-CUST-SUPP",
    "Non-Voice Process Manager": "NV-PROC-MGR",
    "Non-Voice Technical Support Specialist": "NV-TECH-SUPP",
    "NON VOICE": "NV",
    "Operations Manager (Non-Voice)": "OPS-MGR-NV",
    "Operations Manager (Voice)": "OPS-MGR-V",
    "Organizational Development Manager": "ORG-DEV-MGR",
    "Outside Sales Representative": "OUT-SALES",
    "Paid Advertising Specialist (PPC)": "PPC-SPEC",
    "Payroll Clerk": "PAY-CLERK",
    "Payroll Manager": "PAY-MGR",
    "Performance Marketing Manager": "PERF-MKT-MGR",
    "Phone Support Specialist": "PHONE-SUPP",
    "Portfolio Manager": "PORT-MGR",
    "Poster Designer": "POST-DES",
    "Principal Engineer": "PRIN-ENG",
    "Product Marketing Manager": "PROD-MKT-MGR",
    "Public Relations (PR) Manager": "PR-MGR",
    "Python Desktop Developer": "PY-DESK-DEV",
    "Python Developer": "PY-DEV",
    "Quality Analyst (Voice Process)": "QA-VOICE",
    "React Native": "REACT-NAT",
    "ReactJs Developer": "REACT-DEV",
    "Recruiting Assistant": "REC-ASST",
    "Recruiting Manager": "REC-MGR",
    "Recruiting Specialist": "REC-SPEC",
    "Regional Sales Manager": "REG-SALES-MGR",
    "Retail Sales Associate": "RET-SALES",
    "Risk Analyst": "RISK-ANLY",
    "Risk Manager": "RISK-MGR",
    "SaaS Sales Executive (Software as a Service)": "SAAS-SALES",
    "Sales Associate": "SALES-ASSOC",
    "Sales Consultant": "SALES-CONS",
    "Sales Development Representative (SDR)": "SDR",
    "Sales Director": "SALES-DIR",
    "Sales Enablement Manager": "SALES-EN-MGR",
    "Sales Engineer": "SALES-ENG",
    "Sales Executive": "SALES-EXEC",
    "Sales Operations Manager": "SALES-OPS-MGR",
    "Sales Operations Specialist": "SALES-OPS-SP",
    "Sales Representative": "SALES-REP",
    "Sales Support Representative (Voice)": "SALES-SUPP-V",
    "Sales Team Lead (Voice)": "SALES-LEAD-V",
    "Sales Team Leader": "SALES-LEAD",
    "Senior Accountant": "SR-ACCT",
    "Senior Backend Developer": "SR-BE-DEV",
    "Senior Brand Manager": "SR-BRAND-MGR",
    "Senior Content Strategist": "SR-CONT-STRAT",
    "Senior Customer Service Representative": "SR-CSR",
    "Senior Developer": "SR-DEV",
    "Senior DevOps Engineer": "SR-DEVOPS",
    "Senior Digital Marketing Manager": "SR-DIG-MKT-MGR",
    "Senior Financial Analyst": "SR-FIN-ANLY",
    "Senior Frontend Developer": "SR-FE-DEV",
    "Senior Full-Stack Developer": "SR-FULL-DEV",
    "Senior Manager (Call Center Operations)": "SR-MGR-CC-OPS",
    "Senior Manager (Non-Voice Customer Service)": "SR-MGR-NV-CS",
    "Senior Marketing Manager": "SR-MKT-MGR",
    "Senior Mobile App Developer": "SR-MOB-DEV",
    "Senior Non-Voice Support Specialist": "SR-NV-SUPP",
    "Senior Product Marketing Manager": "SR-PROD-MKT-MGR",
    "Senior Sales Executive": "SR-SALES-EXEC",
    "Senior SEO Manager": "SR-SEO-MGR",
    "Senior Software Engineer": "SR-SW-ENG",
    "SEO Assistant": "SEO-ASST",
    "SEO Manager": "SEO-MGR",
    "SEO Specialist": "SEO-SPEC",
    "Social Media Coordinator": "SOC-MED-COORD",
    "Social Media Manager": "SOC-MED-MGR",
    "Social Media Support Executive": "SOC-MED-SUPP",
    "Social Media Support Manager": "SOC-MED-SUPP-MGR",
    "Social Media Support Specialist": "SOC-MED-SUPP-SP",
    "Software Developer": "SW-DEV",
    "Software Engineer": "SW-ENG",
    "Solutions Architect": "SOL-ARCH",
    "Solutions Sales Manager": "SOL-SALES-MGR",
    "Strategic Account Manager": "STRAT-ACCT-MGR",
    "Systems Architect": "SYS-ARCH",
    "Talent Acquisition Specialist": "TAL-ACQ-SPEC",
    "Tax Advisor": "TAX-ADV",
    "Tax Associate": "TAX-ASSOC",
    "Tax Manager": "TAX-MGR",
    "Tax Specialist": "TAX-SPEC",
    "Team Lead (Non-Voice)": "TEAM-LEAD-NV",
    "Team Lead (Voice)": "TEAM-LEAD-V",
    "Technical Director": "TECH-DIR",
    "Technical Lead": "TECH-LEAD",
    "Technical Sales Representative": "TECH-SALES",
    "Technical Support Representative (Non-Voice)": "TECH-SUPP-NV",
    "Technical Support Representative (Voice)": "TECH-SUPP-V",
    "Technical Support Specialist (Voice)": "TECH-SUPP-SP-V",
    "Telemarketer": "TELE-MKT",
    "Telemarketing Executive": "TELE-MKT-EXEC",
    "Territory Sales Manager": "TERR-SALES-MGR",
    "Training and Development Coordinator": "T&D-COORD",
    "Training and Development Manager": "T&D-MGR",
    "Training Specialist (Voice)": "TRAIN-SPEC-V",
    "Treasury Analyst": "TREAS-ANLY",
    "Treasury Manager": "TREAS-MGR",
    "UI/UX Designer": "UI/UX",
    "Video Editor": "VID-EDIT",
    "Vice President of Business Development": "VP-BIZ-DEV",
    "Vice President of Finance": "VP-FIN",
    "Vice President of Human Resources": "VP-HR",
    "Vice President of Marketing": "VP-MKT",
    "Voice": "VOICE",
    "Voice Process Manager": "VOICE-PROC-MGR",
    "VP of Engineering": "VP-ENG",
    "VP of Growth": "VP-GRWTH",
    "VP of Product Marketing": "VP-PROD-MKT",
    "VP of Sales": "VP-SALES",
    "VR/AR Developer (Virtual Reality/Augmented Reality)": "VR/AR-DEV",
    "Wealth Manager": "WLTH-MGR",
    "Web Developer": "WEB-DEV",
};
